service: weather-app-backend
runtime: custom
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
env_variables:
  CORS_ALLOWED_ORIGINS: "https://weather-app-213413.appspot.com,http://weather-app-213413.appspot.com"
  APPID: REPLACE_WITH_REAL_API_KEY

